language: java

git:
  depth: false
  quiet: true

dist: focal

cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk15
  - openjdk15

services:
  - redis

addons:
  mariadb: "10.5"

before_install:
  - sudo mysql -e 'CREATE DATABASE blog;'
  - sudo mysql -e 'SELECT host,user,password FROM mysql.user;'
  - cat /etc/mysql/mariadb.conf.d/50-server.cnf

after_success:
  - bash <(curl -s https://codecov.io/bash)
