language: java

git:
  depth: false
  quiet: true

cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk15
  - openjdk15

services:
  - redis

addons:
  mariadb: "10.5"

# Travis 的 Mariadb 没有配置用户会导致无法登录，需要手动处理下
before_install:
  - mariadb -e "CREATE DATABASE blog;"
  - mariadb -e "SET PASSWORD FOR 'root'@'localhost' = '';"
  - mariadb -e "FLUSH PRIVILEGES;"

after_success:
  - bash <(curl -s https://codecov.io/bash)
