language: java

git:
  depth: false
  quiet: true

dist: focal

cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk15
  - openjdk15

services:
  - redis

addons:
  mariadb: "10.5"

before_install:
  - sudo mysql -e "CREATE DATABASE blog;"
  - sudo mysql -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('');"
  - sudo mysql -e "FLUSH PRIVILEGES;"

after_success:
  - bash <(curl -s https://codecov.io/bash)
