spring:

  # 你需要先创建数据库，SpringBoot能够使用 resources/schema.sql 自动建表
  datasource:
    url: jdbc:mariadb://localhost:3306/blog?allowMultiQueries=true
    username: root
    password: foobar123456
    driver-class-name: org.mariadb.jdbc.Driver

  redis:
    host: localhost
    port: 6375
    password: foobar123456

kaciras:

  # OAuth2 可以通过代理访问第三方服务，特别是在墙内访问Google账户时有用
#  http-client-proxy: "localhost:1080"

  session:
    cookie:
      domain: localhost

  development:
    admin-principal: false

  cors:
    allowed-origins: "*"

  rate-limit:

    # 目前单页最大4个请求，保守起见 *4 倍，每秒 2 个也比较高了。
    generic:
      rate: 2
      bucket-size: 16

    # 对非幂等请求的限速：30秒6个，半小时54个，一天约220个
    effective:
      - bucket-size: 6
        rate: 0.2
      - bucket-size: 54
        rate: 0.03
      - bucket-size: 220
        rate: 0.0025

  # 本系统支持 OAuth2 登录，取消下面的注释并填写 client-id 和 client-secret 即可启用
#  oauth2:
    # 前端页面的域名
#    www-host: localhost
#    google:
#      client-id: <your client-id>
#      client-secret: <your client-secret>
#    github:
#      client-id: <your client-id>
#      client-secret: <your client-secret>

blog:

  draft:
    delete-after-publish: false