server:

  ssl:
    enabled: true
    key-store: /path/to/key-store.pfx
    key-store-type: PKCS12
    key-store-password: foobar123456

spring:

  # 你需要先创建数据库，SpringBoot能够使用 resources/schema.sql 自动建表
  datasource:
    url: jdbc:mariadb://localhost:3306/blog?allowMultiQueries=true
    username: root
    password: foobar123456
    driver-class-name: org.mariadb.jdbc.Driver

  redis:
    host: localhost
    port: 6375
    password: foobar123456

kaciras:

#  http-client-proxy: "localhost:1080"

  development:
    admin-principal: false

  cors:
    allowed-origins: "*"

  rate-limit:

    generic:
      rate: 5
      bucket-size: 20

    effective:
      - bucket-size: 6
        rate: 0.2
      - bucket-size: 60
        rate: 0.03
      - bucket-size: 400
        rate: 0.005

  oauth:

    www-host: localhost

    google:
      client-id: <your client-id>
      client-secret: <your client-secret>

    github:
      client-id: <your client-id>
      client-secret: <your client-secret>

blog:

  draft:
    delete-after-publish: false