server:

  ssl:
    enabled: true
    key-store: D:\\Coding\\Utils\\dev.pfx
    key-store-type: PKCS12
    key-store-password: 666666

spring:

  datasource:
    url: jdbc:mariadb://192.168.0.11:3316/blog?allowMultiQueries=true
    username: root
    password: IY*J<0+T.[Skcoxd
    driver-class-name: org.mariadb.jdbc.Driver

  redis:
    host: 192.168.0.11
    port: 33671
    password: ZuDNpaB7]vv_iBynJG6ZwPexPPewP]kf

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#                   Following is the non-spring settings
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

draft:
  delete-after-publish: false

discuss:
  disable: false
  anonymous: true

kaciras:
  cors:
    origins: "*"
  development:
    admin-principal: true
  #   delay: 3s
