server:
  http-port: 2374
  port: 2375

  ssl:
    enabled: true
    key-store: D:\\Coding\\Utils\\dev.pfx
    key-store-type: PKCS12
    key-store-password: 666666

  http2:
    enabled: true

  compression:
    enabled: true
    mime-types: text/html,text/css,text/plain,application/javascript,application/json,application/xml
    min-response-size: 4096

  tomcat:
    max-threads: 4
    accept-count: 512

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.admin.SpringApplicationAdminJmxAutoConfiguration
      - org.springframework.boot.autoconfigure.jms.JmsAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.JdbcTemplateAutoConfiguration
      - org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration

  main:
    banner-mode: "off"

  mvc:
    favicon:
      enabled: false

  jmx:
    enabled: false

  data:
    web:
      pageable:
        page-parameter: start
        size-parameter: count

  datasource:
    url: jdbc:mariadb://localhost:3316/Blog?allowMultiQueries=true
    username: root
    password: IY*J<0+T.[Skcoxd
    driver-class-name: org.mariadb.jdbc.Driver

  redis:
    host: 192.168.0.11
    port: 33671
    password: ZuDNpaB7]vv_iBynJG6ZwPexPPewP]kf

  session:
    store-type: redis
    redis:
      namespace: kx

  jackson:
    date-format: yyyy-MM-dd HH:mm #这个只用于java.util.Date这些老API

mybatis:
  mapper-locations: classpath:result-map.xml

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#                   Following is the non-spring settings
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

temporary-data: true
data-directory: data
debug-permission: true

web:
  cors-origin: "*"
  csrf-verify: true

draft:
  delete-after-publish: true

discuss:
  anonymous: true
