server:
  port: 2375

  http2:
    enabled: true

  compression:
    enabled: true
    mime-types: text/html,text/css,text/plain,application/javascript,application/json,application/xml
    min-response-size: 4096

  tomcat:
    max-threads: 2

spring:

  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.admin.SpringApplicationAdminJmxAutoConfiguration
    - org.springframework.boot.autoconfigure.jms.JmsAutoConfiguration
    - org.springframework.boot.autoconfigure.jdbc.JdbcTemplateAutoConfiguration
    - org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
    - org.springframework.boot.autoconfigure.task.TaskExecutionAutoConfiguration
    - org.springframework.boot.autoconfigure.websocket.servlet.WebSocketServletAutoConfiguration

    - org.springframework.boot.autoconfigure.web.client.RestTemplateAutoConfiguration
    - org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration

  main:
    banner-mode: "off"

  mvc:
    favicon:
      enabled: false

    # 全站AJAX，不存在表单提交PUT、DELETE等问题
    hiddenmethod:
      filter:
        enabled: false

  jmx:
    enabled: false

  data:
    web:
      pageable:
        page-parameter: start
        size-parameter: count

  session:
    store-type: redis
    timeout: 30d
    redis:
      namespace: kx

  jackson:
    date-format: yyyy-MM-dd HH:mm # 这个只用于java.util.Date这些老API

mybatis:
  mapper-locations: classpath:mybatis/*

  configuration:
    cache-enabled: false

kaciras:
  authorization:
    security-context: true
  cors:
    allow-headers: [X-CSRF-Token, X-Requested-With, Content-Type]
    exposed-headers: Location
    max-age: 864000
