server:

  ssl:
    enabled: true
    key-store: /etc/letsencrypt/live/api.kaciras.net/cert.pfx
    key-store-type: PKCS12
    key-store-password: oruzwlYyV2GDlIfTg1u9

spring:

  datasource:
    url: jdbc:mariadb://localhost:42331/blog?allowMultiQueries=true
    username: blog
    password: rKN:E~[H-EkfL SiWa%1mzSgJ+YuN@[#
    driver-class-name: org.mariadb.jdbc.Driver

  redis:
    host: localhost
    port: 33671
    password: sRewULGr8l&f>Qwr`y>O,y%s^m,YC/=@voo2IbwH@oW&cFG<dh_/ihG\PPZKde:pUa3)!Q.CCqp+0gxy@ks6-5BG1.b`h@u{cWGsA<5/CfM]tl<apSelN.gjK<>x*hu*

draft:
  delete-after-publish: false

logging:
  file: content-service.log

kaciras:

  session:
    cookie:
      domain: kaciras.net

  cors:
    origins: https://blog.kaciras.net

  oauth:
    www-host: blog.kaciras.net

    google:
      client-id: 686605909250-m65kb168sb2gbddhr37bjdon9hklrcc8.apps.googleusercontent.com
      client-secret: q_qqA0tuLiw5WZZzTsZIYFwp

    github:
      client-id: 6e5034c34ee4b1b581d3
      client-secret: 2306a57b3d3a916a77c16b56a9ba45ab5d2cc27a
