server:
  port: 2375

  ssl:
    enabled: true
    key-store: D:\\Coding\\Utils\\dev.pfx
    key-store-type: PKCS12
    key-store-password: 666666

  http2:
    enabled: true

  compression:
    enabled: true
    mime-types: text/html,text/css,text/plain,application/javascript,application/json,application/xml
    min-response-size: 4096

spring:
  main:
    banner-mode: "off"

  datasource:
    url: jdbc:mariadb://localhost:3316/Blog?allowMultiQueries=true
    username: root
    password: IY*J<0+T.[Skcoxd
    driver-class-name: org.mariadb.jdbc.Driver

  redis:
    host: 192.168.0.11
    port: 33671
    password: ZuDNpaB7]vv_iBynJG6ZwPexPPewP]kf

  jackson:
    date-format: yyyy-MM-dd HH:mm #这个只用于java.util.Date这些老API

mybatis:
  mapper-locations: classpath:result-map.xml

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#                   Following is the non-spring settings
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

temporary-data: true
data-directory: data
debug-permission: true

web:
  cors-origin: "*"
  csrf-verify: true

draft:
  delete-after-publish: true

discuss:
  anonymous: true
