server:

  ssl:
    enabled: true
    key-store: /etc/letsencrypt/live/api.kaciras.net/cert.pfx
    key-store-type: PKCS12
    key-store-password: oruzwlYyV2GDlIfTg1u9

spring:

  datasource:
    url: jdbc:mariadb://localhost:42331/blog?allowMultiQueries=true
    username: blog
    password: rKN:E~[H-EkfL SiWa%1mzSgJ+YuN@[#
    driver-class-name: org.mariadb.jdbc.Driver

  redis:
    host: localhost
    port: 33671
    password: sRewULGr8l&f>Qwr`y>O,y%s^m,YC/=@voo2IbwH@oW&cFG<dh_/ihG\PPZKde:pUa3)!Q.CCqp+0gxy@ks6-5BG1.b`h@u{cWGsA<5/CfM]tl<apSelN.gjK<>x*hu*

draft:
  delete-after-publish: false

discuss:
  disable: false
  anonymous: true

logging:
  file: content-service.log

kaciras:
  spring:
    session:
      cookie:
        domain: kaciras.net
  cors:
    origins: https://blog.kaciras.net
  oauth:
    www-host: blog.kaciras.net
