server:

  ssl:
    enabled: true
    key-store: D:\\Coding\\Utils\\dev.pfx
    key-store-type: PKCS12
    key-store-password: 666666

spring:

  datasource:
    url: jdbc:mariadb://192.168.0.11:3316/blog?allowMultiQueries=true
    username: root
    password: IY*J<0+T.[Skcoxd
    driver-class-name: org.mariadb.jdbc.Driver

  redis:
    host: 192.168.0.11
    port: 33671
    password: ZuDNpaB7]vv_iBynJG6ZwPexPPewP]kf

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#                                 custom properties
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

draft:
  delete-after-publish: false

kaciras:

  http-client-proxy: "localhost:2080"

  development:
    admin-principal: false

  cors:
    allowed-origins: "*"

  oauth:
    www-host: localhost
    google:
      client-id: 834515199449-f1ia0v8b3fa5hnvuimrradoetulc5nvi.apps.googleusercontent.com
      client-secret: jT7m_0N5zS-QzuzwGKYnYuFo
    github:
      client-id: 08878e62e2f3cb5be51b
      client-secret: 04b1aebe5770a4458bfa17d79bc5cd1988dcba45
