# 配置一些属性的默认值，此文件属于源码的一部分，如果不改动代码只是运行的话不需要修改。
# 运行所需的环境配置（数据库、密码等）在根目录的 application.yml 里

server:

  http2:
    enabled: true

  compression:
    enabled: true

  tomcat:
    connection-timeout: 10s

  servlet:
    register-default-servlet: false

spring:

  # 排除一些用不到的功能，应该能省点内存吧，如果报错找不到某 Bean 可以先到这里看看哦
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.admin.SpringApplicationAdminJmxAutoConfiguration
      - org.springframework.boot.autoconfigure.availability.ApplicationAvailabilityAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.JdbcTemplateAutoConfiguration
      - org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
      - org.springframework.boot.autoconfigure.task.TaskExecutionAutoConfiguration
      - org.springframework.boot.autoconfigure.task.TaskSchedulingAutoConfiguration
      - org.springframework.boot.autoconfigure.web.client.RestTemplateAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration

      # 暂时用不到 Multipart 和 WebSocket
      - org.springframework.boot.autoconfigure.websocket.servlet.WebSocketServletAutoConfiguration
      - org.springframework.boot.autoconfigure.web.servlet.MultipartAutoConfiguration

  main:
    banner-mode: "off"

    # LTW 自动注入不支持延迟初始化
    lazy-initialization: false

  mvc:
    servlet:
      load-on-startup: 0

  jmx:
    enabled: false

  data:
    web:
      pageable:
        page-parameter: start
        size-parameter: count

  session:
    store-type: redis
    timeout: 30d
    redis:
      namespace: kx

  jackson:

    # 过滤掉为 null 的属性，可以减小体积并隐藏完整的格式
    default-property-inclusion: non_null

    # java.time 里的时间全部序列化为毫秒
    serialization:
      write-date-timestamps-as-nanoseconds: false
      write-dates-as-timestamps: true
      write-enums-using-index: true

    deserialization:
      read-date-timestamps-as-nanoseconds: false

  datasource:
    initialization-mode: always
    continue-on-error: true

mybatis:

  mapper-locations: classpath:mybatis/*

  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    cache-enabled: false
    map-underscore-to-camel-case: true

app:

  authorization:
    csrf:
      skip-safe: false

  session:
    cookie:
      secure: true

  cors:
    allow-credentials: true
    allowed-methods: "*"
    allowed-headers: [ X-CSRF-Token, X-Requested-With, Content-Type ]
    exposed-headers: [ Location, X-RateLimit-Wait ]

  http-client:
    timeout: 8s
    executor: taskScheduler
