name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

      mariadb:
        image: mariadb:10.5
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: blog
        ports:
          - 3306:3306

    steps:
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: mvn -B test

      - uses: codecov/codecov-action@v1
