name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

      mariadb:
        image: mariadb:11
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: blog
        ports:
          - 3306:3306

    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 22

      - uses: actions/checkout@v4

      - run: mvn -B test
